AppBundle\Entity\CategoriaProducto:
    type: entity
    table: categoria_producto
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        codigoCategoria:
            type: string
            nullable: false
            length: 15
            fixed: false
            column: codigo_categoria
        nombreCategoria:
            type: string
            nullable: true
            length: 25
            fixed: false
            column: nombre_categoria
    lifecycleCallbacks: {  }
