AppBundle\Entity\EstadoVentaAsistida:
    type: entity
    table: estado_venta_asistida
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreEstadoVentaAsistida:
            type: string
            nullable: false
            length: 25
            fixed: false
            column: nombre_estado_venta_asistida
    lifecycleCallbacks: {  }
