AppBundle\Entity\Genero:
    type: entity
    table: genero
    id:
        id:
            type: smallint
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        generoNombre:
            type: string
            nullable: false
            length: 45
            fixed: false
            column: genero_nombre
    lifecycleCallbacks: {  }
