AppBundle\Entity\Municipio:
    type: entity
    table: municipio
    indexes:
        fk_municipio_departamento1_idx:
            columns:
                - departamento_id
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreMunicipio:
            type: string
            nullable: true
            length: 25
            fixed: false
            column: nombre_municipio
    manyToOne:
        departamento:
            targetEntity: Departamento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                departamento_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
