AppBundle\Entity\Persona:
    type: entity
    table: persona
    indexes:
        fk_persona_municipio1_idx:
            columns:
                - municipio_id
        fk_persona_tipo_identificacion1_idx:
            columns:
                - tipo_identificacion_id
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 60
            fixed: false
        apellido:
            type: string
            nullable: true
            length: 60
            fixed: false
        identificacion:
            type: string
            nullable: true
            length: 20
            fixed: false
        direccion:
            type: string
            nullable: true
            length: 60
            fixed: false
        telefono:
            type: string
            nullable: true
            length: 15
            fixed: false
    manyToOne:
        municipio:
            targetEntity: Municipio
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                municipio_id:
                    referencedColumnName: id
            orphanRemoval: false
        tipoentificacion:
            targetEntity: TipoIdentificacion
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_identificacion_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
