AppBundle\Entity\Rol:
    type: entity
    table: rol
    id:
        id:
            type: smallint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        rolNombre:
            type: string
            nullable: false
            length: 45
            fixed: false
            column: rol_nombre
        rolValor:
            type: integer
            nullable: false
            unsigned: false
            column: rol_valor
    lifecycleCallbacks: {  }
